version: '3'

services:
  aiohttp:
    build:
      context: .
      dockerfile: ./docker/aiohtpp/Dockerfile
    image: test
    volumes:
      - .:/app
    env_file:
      - "./docker_env/aiohttp/.local"
    ports:
      - "8080:8080"
    command: /start_local
    networks:
      - apinetwork
    stdin_open: true
    tty: true

networks:
    apinetwork:
        driver: bridge
